const path = require('path');
const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./src/routes/index.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "EXPLORER-FOOD-API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3333",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Users",
            "description": "Endpoint de Usuarios"
        },
        {
            "name": "Dishes",
            "description": "Endpoint de Pratos"
        },
        {
            "name": "Orders",
            "description": "Endpoint de Pedidos"
        },
        {
            "name": "Sessions",
            "description": "Endpoint de Sessões"
        },
    ],
    routes:{},
    definitions: {
        User:{
            name:"Name Last Name",
            email: "name@example.com",
            password: "******"
        }
    }
}

doc.routes = {
    '/users': {
      post: {
        tags: ['Users'],
        summary: 'Create a new user',
        description: 'Endpoint to create a new user',
        requestBody: {
          // Definição do corpo da requisição
        },
        responses: {
          // Definição das respostas
        },
      },
      // Outros métodos HTTP para a rota /users
    },
    '/sessions': {
      // Definição dos métodos HTTP para a rota /sessions
    },
    '/dishes': {
      // Definição dos métodos HTTP para a rota /dishes
    },
    '/orders': {
      // Definição dos métodos HTTP para a rota /orders
    },
  };

swaggerAutogen(outputFile, endpointsFiles, doc)
.then(() => {
    require('./src/server.js')
})